Repository magicbell-io/magicbell-react, pull requests merged in 2022-03, with the labels that each got.

#79 fix: don't invoke click handler when clicking embedded links
  src/components/ClickableNotification/ClickableNotification.tsx
  tests/src/components/ClickableNotification/ClickableNotification.spec.tsx
Labels: 🐛 bug

#80 Feature: Dynamic Channel Layout and Custom Label
  .eslintrc.js
  package.json
  src/components/NotificationInbox/private/PreferencesView.tsx
  src/components/UserPreferencesPanel/CategoryPreferences.tsx
  src/components/UserPreferencesPanel/PreferencesCategories.tsx
  stories/Introduction.stories.mdx
  tests/factories/NotificationPreferencesFactory.ts
  tests/lib/deepFreeze.ts
  tests/src/components/NotificationInbox/NotificationInbox.spec.tsx
  tests/src/components/UserPreferencesPanel/CategoryPreferences.spec.tsx
  tests/src/components/UserPreferencesPanel/PreferencesCategories.spec.tsx
  yarn.lock
Labels: Ready for review

#93 chore: make pre-commit script executable
  .husky/pre-commit
Labels: 🛠️ tools

#94 feat: use FloatingNotificationInbox as default Inbox
  README.md
  src/components/MagicBell/MagicBell.tsx
  stories/MagicBell.stories.tsx
  tests/src/components/MagicBell/MagicBell.spec.tsx
Labels: 📦 feature
